image: continuumio/miniconda3:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  #- conda env create -f conda_env.yaml
  #- source activate carla_gym
  - python -V               # Print out python version for debugging

test:
  script:
  #- python setup.py test
  - pip3 install tox flake8
  #- tox -e py36,flake8
  - python3 flake8 ./ --max-line-length 80

#run:
  #script:
  
  #- python setup.py bdist_wheel
  # an alternative approach is to install and run:
  #- pip install dist/*
  # run the command here
  #artifacts:
  #  paths:
  #  - dist/*.whl

#pages:
  #script:
  #- pip install sphinx sphinx-rtd-theme
  #- cd doc ; make html
  #- mv build/html/ ../public/
  #artifacts:
  #  paths:
  #  - public
  #only:
  #- master
